import pygame

walk = [
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Run/Armature_Run_00.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Run/Armature_Run_01.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Run/Armature_Run_02.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Run/Armature_Run_03.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Run/Armature_Run_04.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Run/Armature_Run_06.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Run/Armature_Run_07.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Run/Armature_Run_09.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Run/Armature_Run_10.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Run/Armature_Run_11.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Run/Armature_Run_13.png")
]

idle = [
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Idle/Armature_Idle_00.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Idle/Armature_Idle_01.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Idle/Armature_Idle_02.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Idle/Armature_Idle_03.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Idle/Armature_Idle_04.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Idle/Armature_Idle_05.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Idle/Armature_Idle_06.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Idle/Armature_Idle_07.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Idle/Armature_Idle_08.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Idle/Armature_Idle_09.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Idle/Armature_Idle_10.png")
]

attack = [
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_00.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_01.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_02.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_03.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_04.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_05.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_06.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_07.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_08.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_09.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_10.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_11.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_12.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_13.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_14.png"),
    pygame.image.load(
        "../../media/captures/actions/"
        "Tiles/Character/Animations/Attack/Armature_Attack_15.png")
]